parameters:
#    projet.example.class: projet\symfony2Bundle\Example

services:
#    projet.example:
#        class: %projet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
